---
all:
    hosts:
        104.215.72.107:
            ansible_ssh_private_key_file: ~/.ssh/revature/vm1_rsa
        20.97.12.217:
            ansible_ssh_private_key_file: ~/.ssh/revature/vm1_rsa
        52.142.60.104:
            ansible_ssh_private_key_file: ~/.ssh/vm1_key.pem
    vars:
        ansible_user: eric
